---
blank_issues_enabled: false
contact_links:
  - name: TS Project Template Community Support
    url: https://github.com/jonitoh/ts-project-template/discussions
    about: Please ask and answer questions here.
